"""Type stubs for the compiled extension."""

from collections.abc import Sequence
from typing import Any

import numpy as np
import numpy.typing as npt

CORE_VERSION: str

class ThiessenError(ValueError): ...

class Fitted:
    @property
    def n_draws(self) -> int: ...
    @property
    def model(self) -> str: ...
    @property
    def in_sample_rmse(self) -> float: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def config(self) -> str: ...
    def predict(self, x: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def predict_draws(self, x: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def predict_latent(self, x: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def predict_variance(
        self, x: npt.NDArray[np.float64]
    ) -> npt.NDArray[np.float64]: ...
    def predict_quantiles(
        self, x: npt.NDArray[np.float64], probs: Sequence[float]
    ) -> npt.NDArray[np.float64]: ...
    def credible_interval(
        self, x: npt.NDArray[np.float64], level: float
    ) -> npt.NDArray[np.float64]: ...
    def prediction_interval(
        self, x: npt.NDArray[np.float64], level: float
    ) -> npt.NDArray[np.float64]: ...
    def log_likelihood(
        self, x: npt.NDArray[np.float64], y: npt.NDArray[np.float64]
    ) -> npt.NDArray[np.float64]: ...
    def sigma(self) -> npt.NDArray[np.float64]: ...
    def cell_counts(self) -> npt.NDArray[np.float64]: ...
    def dimension_counts(self) -> npt.NDArray[np.float64]: ...
    def variable_inclusion_proportions(self) -> npt.NDArray[np.float64]: ...
    def to_json(self) -> str: ...
    def __reduce__(self) -> tuple[Any, tuple[str]]: ...

def fit(
    config_json: str,
    x: npt.NDArray[np.float64],
    y: npt.NDArray[np.float64],
    seed: int,
) -> Fitted: ...
def fitted_from_json(json: str) -> Fitted: ...
def validate_config(config_json: str) -> None: ...
